### ISSUE TITLE
To include SCHISM shinnecock tests to test suites

### ISSUE THREAD

**Issue by saeed-moghimi-noaa** [noaa-ocs-modeling/CoastalApp-testsuite#12]

**Comment by platipodium** [comment]
I can do this, please check once I uploaded my test suite

**Comment by saeed-moghimi-noaa** [comment]
@pvelissariou1  Please upload your current work n a branch so me and Carsten can work on it in parallel.  Thanks.

**Comment by platipodium** [comment]
This is https://github.com/noaa-ocs-modeling/CoastalApp-testsuite/pull/1

Please test and merge

**Comment by pvelissariou1** [comment]
I will. I am deploying a develop branch (open) with all latest updates so
we can all work on this (pushing, editing, etc)

Panagiotis Velissariou, Ph.D., P.E.
UCAR Scientist
National Ocean and Atmospheric Administration
National Ocean Service
Office of Coast Survey CSDL/CMMB
Physical Scientist - Project Lead
cell: (205) 227-9141
email: ***@***.***

**Comment by pvelissariou1** [comment]
Closing this as completed.
