### ISSUE TITLE
Compile required libraries/modules on Hera, TACC, Orion, PWorks

### ISSUE THREAD

**Issue by saeed-moghimi-noaa** [noaa-ocs-modeling/CoastalApp-testsuite#13]

**Comment by saeed-moghimi-noaa** [comment]
@pvelissariou1 
Hi Tkais, please update here what modules and why we need those on Hera?  Thanks.

**Comment by saeed-moghimi-noaa** [comment]
@pvelissariou1  Please follow up with Hera Help desk and find out what the is the process now?

**Comment by saeed-moghimi-noaa** [comment]
To use the modules try:
```
module use /scratch2/STI/coastal/common/apps/modulefiles
```

**Comment by pvelissariou1** [comment]
New modules and libraries have been compiled and installed on hera. Will be working on ufs-coastal tests to identify issues with ufs-coastal.

**Comment by pvelissariou1** [comment]
Will document the details of availability and implementation in different platforms. ...

**Comment by pvelissariou1** [comment]
The libraries and the new module system were compiled on "hera" and subequently ported to the ParallelWorks, Orion and TACC (Frontera, Stampede) HPC platforms. The ParallelWorks port is identical to the "hera" system except the installation path. The list of the libraries compiled and installed is as follows:

1. **HDF**        Versions: 4.2.15, 4.2.16
2. **HDF5**      Versions: 1.10.7, 1.10.9 (serial and parallel versions)
3. **NetCDF**  Versions: 4.7.4, 4.9.2 (serial and parallel versions)
      - Version 4.7.4 includes: netCDF 4.7.4, netCDF-cxx4 4.3.1, netCDF-Fortran 4.5.3
      - Version 4.9.2 includes: netCDF 4.9.2, netCDF-cxx4 4.3.1, netCDF-Fortran 4.6.0
4. **szip**         Versions: 2.1.1 (old, legacy compression library for HDF5)
5. **libaec**     Versions: 1.0.6 (new, szip compatible,  compression library for HDF5)

**Comment by pvelissariou1** [comment]
This should be closed. Now spack-stack is fully functional (no major bugs) as of verion 1.5.0.
We should move using spack-stack on hera, orion, hercules and parallel works. Regarding TACC, we have to use what is installed in the host OS + libraries I have built for specific compiler versions.
