### ISSUE TITLE
`PARMETIS` requirement

### ISSUE THREAD

**Issue by SorooshMani-NOAA** [noaa-ocs-modeling/CoastalApp-testsuite#5]
Testing CoastalApp on RDHPCS ParallelWorks, I had to download parmetis first using `scripts/download_parmetis.sh` in the `CoastalApp` build process. Then to build I had to use 
```bash
./build.sh --compiler intel --platform hera --component "atmesh pahm adcirc ww3"  -y --tp parmetis
```
Note the additional `--tp parmetis` flag.

Thanks to @pvelissariou1 for the help. I'm just creating this issue so that later the readme file gets updated.

**Comment by pvelissariou1** [comment]
Thanks Soroosh. I will update all Readme files (including PaHM) with
detailed instructions.
Please, keep updating the issues with the problems you encounter (including
PW).

Panagiotis Velissariou, Ph.D., P.E.
UCAR Scientist
National Ocean and Atmospheric Administration
National Ocean Service
Office of Coast Survey CSDL/CMMB
Physical Scientist - Project Lead
cell: (205) 227-9141
email: ***@***.***

**Comment by pvelissariou1** [comment]
This issue was addressed. README.md file was updated to reflect the changes regarding ParMETIS.
