### ISSUE TITLE
`ADCIRC` clone error

### ISSUE THREAD

**Issue by SorooshMani-NOAA** [noaa-ocs-modeling/CoastalApp-testsuite#6]
After setting up the Git credentials, I still have issue with the `clone` process. On my local machine it goes through fine, but on ParallelWorks I get the following error when fetching ADCIRC:
```
fatal: reference is not a tree: 38d8d4effff115a11114a9935dd1571829e08577
```
And then at the end of `clone` process for the whole `CoastalApp` repo I get:
```
Unable to checkout '38d8d4effff115a11114a9935dd1571829e08577' in submodule path 'ADCIRC'
```

This is after executing:
```
git clone --recurse-submodules https://github.com/noaa-ocs-modeling/CoastalApp -b develop
```
with the GitHub token set properly

**Comment by pvelissariou1** [comment]
Closing this as completed. The ADCIRC pointers have been fixed in CoastalApp.
