### ISSUE TITLE
`ESMF` issue on ParallelWorks

### ISSUE THREAD

**Issue by SorooshMani-NOAA** [noaa-ocs-modeling/CoastalApp-testsuite#7]
Trying to compile `CoastalApp` using `HERA` platform out of the box didn't work on PW platform. One of the main ingredients missing is ESMF library.

The following error occurred:
```
ake[1]: Entering directory `/home/Soroosh.Mani/sandbox/CoastalApp-testsuite/CoastalApp/ATMESH'

c     -I.  -I/include/    -I/include/    -L.  -L/lib/ -L/lib/ -DWITHPETLISTS_on  -DESMF_VERSION_MAJOR= atmesh_mod.F90
make[1]: c: Command not found
make[1]: [atmesh_mod.o] Error 127 (ignored)


c     -I.  -I/include/    -I/include/    -L.  -L/lib/ -L/lib/ -DWITHPETLISTS_on  -DESMF_VERSION_MAJOR= atmesh.F90
make[1]: c: Command not found
make[1]: [atmesh.o] Error 127 (ignored)

ar rv libatmesh_cap.a atmesh.o atmesh_mod.o
ar: creating libatmesh_cap.a
ar: atmesh.o: No such file or directory
make[1]: *** [libatmesh_cap.a] Error 1
make[1]: Leaving directory `/home/Soroosh.Mani/sandbox/CoastalApp-testsuite/CoastalApp/ATMESH'
make: *** [/home/Soroosh.Mani/sandbox/CoastalApp-testsuite/CoastalApp/ATMESH_INSTALL/atmesh.mk] Error 2
```

**Comment by SorooshMani-NOAA** [comment]
After this per @pvelissariou1 suggestion I tried getting `esmf` from Hera; to do so, I loaded `esmf` module following steps in [`modulefiles/envmodules_intel.hera`](https://github.com/noaa-ocs-modeling/CoastalApp/blob/e8071cb18e1c7bbd53635e6d10e0b40f031591d0/modulefiles/envmodules_intel.hera#L17-L25) then based on the location referred to by `ESMFMKFILE` environment, transferred the `esmf` `lib` and `bin` to PW and then set the `ESMFMKFILE` to the location of ESMF library on PW. In the end I still had issues compiling:
```
atmesh_mod.F90(17): error #7002: Error in opening the compiled module file.  Check INCLUDE paths.   [ESMF]
  use ESMF
------^
atmesh_mod.F90(18): error #7002: Error in opening the compiled module file.  Check INCLUDE paths.   [NUOPC]
  use NUOPC
------^
atmesh_mod.F90(19): error #7002: Error in opening the compiled module file.  Check INCLUDE paths.   [NETCDF]
  USE netcdf
------^
atmesh_mod.F90(37): error #6683: A kind type parameter must be a compile-time constant.   [ESMF_KIND_R8]
    real(ESMF_KIND_R8), allocatable     :: LONS(:), LATS(:),TIMES(:)
```

**Comment by pvelissariou1** [comment]
Soroosh hi,

Just comment out the "module load emf" line in the modulefile.
Before running the build.sh script set the environment variable
export ESMFMKFILE=your_esmf.mk_location
and then run the build script.
The script should pick up the environment variable ESMFMKFILE and resume
the compilation.
See if that works on PW.

Takis

Panagiotis Velissariou, Ph.D., P.E.
UCAR Scientist
National Ocean and Atmospheric Administration
National Ocean Service
Office of Coast Survey CSDL/CMMB
Physical Scientist - Project Lead
cell: (205) 227-9141
email: ***@***.***

**Comment by SorooshMani-NOAA** [comment]
Commenting out `module load esmf` doesn't help either, I get the same error as before. It is possible that PW doesn't have some of the compiler module version used to compile the esmf on Hera

**Comment by pvelissariou1** [comment]
It is possible. Let me login on hera and I'll send an invitation to chat on
this.

Panagiotis Velissariou, Ph.D., P.E.
UCAR Scientist
National Ocean and Atmospheric Administration
National Ocean Service
Office of Coast Survey CSDL/CMMB
Physical Scientist - Project Lead
cell: (205) 227-9141
email: ***@***.***

**Comment by pvelissariou1** [comment]
Soroosh,

I tested the approach on setting the ESMFMKFILE variable on hera (without
loading the esmf module) and compiled CoastalApp just
fine (ATMESH+ADCIRC). I am sending a google invitation.

Takis

Panagiotis Velissariou, Ph.D., P.E.
UCAR Scientist
National Ocean and Atmospheric Administration
National Ocean Service
Office of Coast Survey CSDL/CMMB
Physical Scientist - Project Lead
cell: (205) 227-9141
email: ***@***.***

**Comment by pvelissariou1** [comment]
Closing as completed with the installation of the new module / libraries system.
